# Workflow name
name: Build
on:
  # When it will be triggered
  # And in which branch
  pull_request:
  push:
    branches:
      - feature/memories_feature_test
# Where will they run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        ## - name: Set up our JDK environment
        ## uses: actions/setup-java@v1.4.3
          ## with:
        ## java-version: 1.8
## Build all our Build Types at once ##
        ## - name: Build all artifacts
        ## id: buildAllApks
        ## uses: eskatos/gradle-command-action@v1.3.3
          ## with:
          ## gradle-version: current
          ## wrapper-cache-enabled: true
          ## dependencies-cache-enabled: true
          ## configuration-cache-enabled: true
        ## arguments: assembleRelease
      - name: Run Unit Tests
        ##run: ./gradlew testDebugUnitTest
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          target: default
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace

      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: /home/runner/work/my_memories/my_memories/app/build/reports/coverage/

  upload-to-codecov:
    needs:  [build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
